apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: guidking-cert
spec:
  secretName: guidking-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: guidking.com
  dnsNames:
    - guidking.com
    - www.guidking.com
    - api.guidking.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - guidking.com
          - www.guidking.com
          - api.guidking.com

