apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guidking-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: guidking-api
  template:
    metadata:
      labels:
        component: guidking-api
    spec:
      containers:
        - name: guidking-api
          image: "gcr.io/guidking/guidking-api:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PWD
              valueFrom:
                secretKeyRef:
                  name: secrecy
                  key: mongo_password
          ports:
            - name: http
              containerPort: 3000
          resources:
            limits:
              cpu: 0.1
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 1
