apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - guidking.com
        - www.guidking.com
        - api.guidking.com
      secretName: guidking-cert
  rules:
  - host: guidking.com
    http:
      paths:
      - path: /
        backend:
          serviceName: guidking-com-service
          servicePort: 80
  - host: www.guidking.com
    http:
      paths:
      - path: /
        backend:
          serviceName: guidking-com-service
          servicePort: 80
  - host: api.guidking.com
    http:
      paths:
      - path: /
        backend:
          serviceName: guidking-api-service
          servicePort: 3000
